name: 'modern-spring-boot'
services:

  postgres:
    image: postgres:17-alpine
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432"