name: Build

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'zulu' ]
        java: [ '24' ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }} (${{ matrix.distribution }})
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify

